<?php
/** @var \Andriy\Points\Block\Widget\PointsList $block */
?>
<style>
    /* Set the size of the div element that contains the map */
    #map {
        height: 400px;
        /* The height is 400 pixels */
        width: 100%;
        /* The width is the width of the web page */
    }
</style>
<?php
$points = $block->getPointsCollection();
?>
<?php foreach ($points as $point): ?>
    <div>
        <a onclick="getLocation('<?php echo $point->getLatitude(); ?>','<?php echo $point->getlongitude(); ?>')">
            <?php echo $point->getName(); ?>
            <?php echo $point->getLacation(); ?>
            <?php echo $point->getAddress(); ?>
            <?php echo $point->getLatitude(); ?>
            <?php echo $point->getlongitude(); ?>
            <?php echo $block->getShipping($point->getData('shipping_id')); ?>

        </a>
    </div>

<?php endforeach; ?>
<div id="map"></div>

<script>
    function getLocation(lat, lon) {
        console.log(lat);
    }

    function initMap() {

        // The location of Uluru
        getLocation(lat, lon){

            console.log('asd');
            const uluru = {lat: lat, lng: lon};
        }

        // The map, centered at Uluru
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 4,
            center: uluru,
        });
        // The marker, positioned at Uluru
        const marker = new google.maps.Marker({
            position: uluru,
            map: map,
        });
    }

    window.initMap = initMap;
</script>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3UtvvfKy6lurr--S0xuzcTYQKoWHx73E&callback=initMap&v=weekly"
    defer
></script>
